// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5e0_wnlmUI5VlB3tqFuO7yA3ix8kH-XM',
    appId: '1:103188516518:web:ad61a7a09661a96b806e67',
    messagingSenderId: '103188516518',
    projectId: 'library-system-92d58',
    authDomain: 'library-system-92d58.firebaseapp.com',
    storageBucket: 'library-system-92d58.firebasestorage.app',
    measurementId: 'G-8TGR6V034W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgDxIdtwp0rTmJYBtq_hbJdxw7sFWHlcA',
    appId: '1:103188516518:android:e76657eb13e689c7806e67',
    messagingSenderId: '103188516518',
    projectId: 'library-system-92d58',
    storageBucket: 'library-system-92d58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6rfdGHtvUDu01Q2ndsSkDmLTR-j2_R3E',
    appId: '1:103188516518:ios:95083ef095f40a6f806e67',
    messagingSenderId: '103188516518',
    projectId: 'library-system-92d58',
    storageBucket: 'library-system-92d58.firebasestorage.app',
    iosClientId: '103188516518-l7004lmd2euearmrh6c471tnu1dvjql4.apps.googleusercontent.com',
    iosBundleId: 'com.example.problem2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6rfdGHtvUDu01Q2ndsSkDmLTR-j2_R3E',
    appId: '1:103188516518:ios:95083ef095f40a6f806e67',
    messagingSenderId: '103188516518',
    projectId: 'library-system-92d58',
    storageBucket: 'library-system-92d58.firebasestorage.app',
    iosClientId: '103188516518-l7004lmd2euearmrh6c471tnu1dvjql4.apps.googleusercontent.com',
    iosBundleId: 'com.example.problem2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5e0_wnlmUI5VlB3tqFuO7yA3ix8kH-XM',
    appId: '1:103188516518:web:10509e95d343862d806e67',
    messagingSenderId: '103188516518',
    projectId: 'library-system-92d58',
    authDomain: 'library-system-92d58.firebaseapp.com',
    storageBucket: 'library-system-92d58.firebasestorage.app',
    measurementId: 'G-KZDEF1691K',
  );
}
